#!/usr/bin/env python3
"""An independent TLR/1 canon implementation, sharing no code with any SDK.

Deliberately duplicated. Importing the Python SDK here would be tidier and would
destroy the point: a canon bug would then be present in both the thing under
test and the thing testing it. Duplication is the mechanism, not an oversight.


The corpus is generated by `tideline-proto`, so replaying it in Rust only proves
the crate agrees with itself. This script re-derives every hash from the spec
alone. It is the guard against a canon change that is wrong in the same way in
both the generator and the verifier.

    python3 conformance/independent_check.py

Exits non-zero on any mismatch.
"""

import hashlib
import json
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ZERO = b"\x00" * 32


def sha256(data: bytes) -> bytes:
    return hashlib.sha256(data).digest()


def _end_of_string(src: str, i: int) -> int:
    """Index just past the closing quote of the string starting at ``i``."""
    i += 1
    while i < len(src):
        if src[i] == "\\":
            i += 2
            continue
        if src[i] == '"':
            return i + 1
        i += 1
    raise ValueError("unterminated string")


def _end_of_value(src: str, i: int) -> int:
    """Index just past the value starting at ``i``."""
    if src[i] == '"':
        return _end_of_string(src, i)
    if src[i] in "{[":
        depth = 0
        while i < len(src):
            if src[i] == '"':
                i = _end_of_string(src, i)
                continue
            if src[i] in "{[":
                depth += 1
            elif src[i] in "}]":
                depth -= 1
                if depth == 0:
                    return i + 1
            i += 1
        raise ValueError("unterminated object or array")
    while i < len(src) and src[i] not in " \t\n\r,}]":
        i += 1
    return i


def raw_metadata(src: str):
    """The exact byte span of the top-level ``metadata`` member's value.

    Canon commits to the bytes the client sent. Parsing and re-serialising would
    normalise spacing and key order, which is exactly what must not happen.

    This walks members at the top level rather than searching for
    ``"metadata":``. A search finds a nested ``metadata`` key first whenever one
    precedes the real member, and hashes the wrong bytes.
    """
    i = src.index("{") + 1
    while i < len(src):
        while src[i] in " \t\n\r":
            i += 1
        if src[i] == "}":
            return None
        key_end = _end_of_string(src, i)
        key = json.loads(src[i:key_end])
        i = key_end
        while src[i] in " \t\n\r":
            i += 1
        assert src[i] == ":", f"expected ':' at {i}"
        i += 1
        while src[i] in " \t\n\r":
            i += 1
        value_end = _end_of_value(src, i)
        if key == "metadata":
            return src[i:value_end]
        i = value_end
        while i < len(src) and src[i] in " \t\n\r":
            i += 1
        if i < len(src) and src[i] == ",":
            i += 1
            continue
        return None
    return None


def canon(event_json: str) -> bytes:
    e = json.loads(event_json)
    redacted = e.get("redacted") or {}

    def digest(field, value):
        if value is not None:
            return sha256(value.encode("utf-8"))
        if field in redacted:
            return bytes.fromhex(redacted[field])
        return ZERO

    meta = raw_metadata(event_json)
    out = (
        b"tlr1\n"
        + struct.pack(">Q", e["seq"])
        + struct.pack(">Q", e["ts"])
        + sha256(e["kind"].encode("utf-8"))
        + digest("role", e.get("role"))
        + digest("name", e.get("name"))
        + digest("content", e.get("content"))
        + digest("metadata", meta)
    )
    if len(out) != 181:
        raise AssertionError(f"canon is {len(out)} bytes, expected 181")
    return out


def main() -> int:
    path = os.path.join(ROOT, "conformance", "corpus", "events.json")
    with open(path, encoding="utf-8") as fh:
        corpus = json.load(fh)

    failures = []
    for v in corpus["vectors"]:
        c = canon(v["event_json"])
        prev = bytes.fromhex(v["prev_hash"])
        ok = (
            hashlib.sha256(c).hexdigest() == v["canon_sha256"]
            and hashlib.sha256(c + prev).hexdigest() == v["hash"]
        )
        print(f"  {'PASS' if ok else 'FAIL'}  {v['name']}")
        if not ok:
            failures.append(v["name"])

    if failures:
        print(f"\nMISMATCH in {len(failures)} vector(s): {', '.join(failures)}")
        return 1
    print(f"\n{len(corpus['vectors'])} vectors reproduced independently")
    return 0


if __name__ == "__main__":
    sys.exit(main())
